version: '3.7'

services:
  server:
    image: "everglades-server:latest"
  agent:
    image: "${agent_image}:latest"
    environment:
      - PLAYER_NUM=0
      - PUB_SOCKET=5555
  opp-agent:
    image: "everglades-agent:latest"
    environment:
      - PLAYER_NUM=1
      - PUB_SOCKET=5556