version: '3.7'

services:
  server:
    image: "everglades-server:latest"
  agent:
    image: "everglades-agent-random-delayed:latest"
#    image: "${agent_image}:latest"
    environment:
      - PLAYER_NUM=0
      - PUB_SOCKET=5555
  opp-agent:
#    image: "${agent_image}:latest"
    image: "everglades-agent-random:latest"
    environment:
      - PLAYER_NUM=1
      - PUB_SOCKET=5556