FROM python:3.6-slim-stretch

RUN mkdir env/

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY env ./env/

RUN pip install -e /env/gym-everglades

COPY random_agent.py .

CMD ["python3", "-u", "random_agent.py"]