FROM python:3.6-slim-stretch

RUN mkdir env resources

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY env /env

RUN pip install -e /env/gym-everglades

COPY random_agent.py .
COPY resources/logger.py /resources

EXPOSE 5555 5556 5563

ENV PYTHONPATH "${PYTHONPATH}:/env"

CMD python3 -u random_agent.py